Platform 1946 signature single account flag
getphyllo/phyllo-connect-reactnative pull request #14
Opened 2022-11-07 05:23 UTC by erpankajpatel

- signature changes and sing account flag

2022-11-08 17:42 UTC, akshaybhalotia requested changes

2022-11-08 17:42 UTC, akshaybhalotia commented on android/src/main/java/com/phylloconnect/PhylloConnectModule.kt
> +            "singleAccount" to singleAccount
Same comment - shouldn't be exposed

2022-11-08 17:42 UTC, akshaybhalotia commented on example/src/App.js
> +    const singleAccount = true
Shouldn't be exposed

2022-11-08 17:42 UTC, akshaybhalotia commented on example/src/App.js
> +        singleAccount
Shouldn't be exposed

2022-11-08 17:42 UTC, akshaybhalotia commented on ios/PhylloConnectModule.m
> +RCT_EXTERN_METHOD(initialize:(NSString *)clientDisplayName:(NSString *)token:(NSString *)userId:(NSString *)environment:(NSString *)workPlatformId:(BOOL *)singleAccount)
Shouldn't be exposed

2022-11-08 17:42 UTC, akshaybhalotia commented on ios/PhylloConnectModule.swift
> +    func initialize(clientDisplayName:String,token:String,userId:String ,environment:String, workPlatformId:String,singleAccount:Bool = false) {
Shouldn't be exposed

2022-11-08 17:42 UTC, akshaybhalotia commented on ios/PhylloConnectModule.swift
> +        phylloConfig["singleAccount"] = singleAccount
Shouldn't be exposed

2022-11-08 17:42 UTC, akshaybhalotia commented on src/PhylloConnect.ts
> +  singleAccount?: Boolean
Shouldn't be exposed

2022-11-08 17:42 UTC, akshaybhalotia commented on src/PhylloConnect.ts
> +    singleAccount,
Shouldn't be exposed

2022-11-08 17:42 UTC, akshaybhalotia commented on src/PhylloConnect.ts
> +      singleAccount
Shouldn't be exposed

2022-11-09 11:22 UTC, akshaybhalotia approved these changes

2022-11-09 11:43 UTC, chiragphyllo approved these changes

2022-11-09 11:43 UTC, merged